# Generated by Django 3.2.3 on 2021-06-14 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id_Catalogo', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID del catalogo')),
                ('nombreCatalogo', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
                ('imgCatalogo', models.ImageField(blank=True, default='tienda/static/tienda/img/no_img.jpg', null=True, upload_to='media/catalogo')),
            ],
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut del Comprador')),
                ('nombre', models.CharField(max_length=35, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=35, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=16, verbose_name='Teléfono')),
                ('email', models.CharField(max_length=14, verbose_name='Correo Electrónico')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_Producto', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID del producto')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='Nombre del Producto')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('stock', models.IntegerField(null=True, verbose_name='Stock')),
                ('talla', models.CharField(max_length=4, null=True, verbose_name='Talla')),
                ('imgProducto', models.ImageField(blank=True, default='tienda/static/tienda/img/no_img.jpg', null=True, upload_to='media/producto')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.catalogo', verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_Pedido', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID del pedido')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.comprador')),
            ],
        ),
        migrations.CreateModel(
            name='detallePedido',
            fields=[
                ('id_detallePedido', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID del detallePedido')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad del producto')),
                ('codPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.pedido', verbose_name='Codigo de Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto', verbose_name='Codigo de Producto')),
            ],
        ),
    ]
