# Generated by Django 3.2.4 on 2021-07-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='id_Oferta',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID de la oferta'),
        ),
    ]
